name: Snowflake DCM - Plan

on:
  pull_request:
    branches: [dev, uat, main]


env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SF_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}

jobs:
  plan:
    name: Execute Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install snowflake-cli-labs
      
      - name: Determine Target
        run: |
          if [[ "${{ github.base_ref }}" == "dev" ]]; then echo "TARGET=DCM_DEV" >> $GITHUB_ENV; fi
          if [[ "${{ github.base_ref }}" == "uat" ]]; then echo "TARGET=DCM_UAT" >> $GITHUB_ENV; fi
          if [[ "${{ github.base_ref }}" == "main" ]]; then echo "TARGET=DCM_PROD" >> $GITHUB_ENV; fi
          
      - name: Run DCM Plan
        run: snow dcm plan --target $TARGET --temporary-connection